version: '3.8'

services:
  wildholz-pitch-deck:
    build:
      context: .
      dockerfile: Dockerfile
    image: wildholz-pitch-deck:local
    container_name: wildholz_presentation
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
